//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsl_taskqueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adsl_taskqueue()
        {
            this.customerproduct = new HashSet<adsl_customerproduct>();
            this.stockmovement = new HashSet<adsl_stockmovement>();
            this.taskqueue1 = new HashSet<adsl_taskqueue>();
            this.taskqueue2 = new HashSet<adsl_taskqueue>();
        }
    
        public int taskorderno { get; set; }
        public int taskid { get; set; }
        public Nullable<int> previoustaskorderid { get; set; }
        public Nullable<int> relatedtaskorderid { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<int> attachedobjectid { get; set; }
        public Nullable<System.DateTime> attachmentdate { get; set; }
        public Nullable<int> attachedpersonelid { get; set; }
        public Nullable<System.DateTime> appointmentdate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> consummationdate { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> assistant_personel { get; set; }
        public string fault { get; set; }
    
        public virtual adsl_personel asistanPersonel { get; set; }
        public virtual adsl_personel attachedpersonel { get; set; }
        public virtual adsl_personel personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_customerproduct> customerproduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_stockmovement> stockmovement { get; set; }
        public virtual adsl_taskstatepool taskstatepool { get; set; }
        public virtual adsl_task task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_taskqueue> taskqueue1 { get; set; }
        public virtual adsl_taskqueue relatedTaskQueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_taskqueue> taskqueue2 { get; set; }
        public virtual adsl_taskqueue previousTaskQueue { get; set; }
        public virtual customer attachedcustomer { get; set; }
    }
}
