//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsl_stockstatus
    {
        public int toobject { get; set; }
        public int toobjecttype { get; set; }
        public int stockcardid { get; set; }
        public int INPUT { get; set; }
        public int OUTPUT { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual adsl_personel personel { get; set; }
    }
}
