//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsl_customerdocument
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> attachedobjecttype { get; set; }
        public Nullable<int> taskqueueid { get; set; }
        public Nullable<int> documentid { get; set; }
        public string documenturl { get; set; }
        public Nullable<System.DateTime> receiptdate { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
