//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsl_customerproduct
    {
        public int id { get; set; }
        public Nullable<int> taskid { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> campaignid { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual adsl_taskqueue taskqueue { get; set; }
        public virtual adsl_campaigns campaigns { get; set; }
    }
}
