//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class adsl_personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adsl_personel()
        {
            this.attachedTaskqueue = new HashSet<adsl_taskqueue>();
            this.attachedtaskqueue = new HashSet<adsl_taskqueue>();
            this.updatedTaskqueue = new HashSet<adsl_taskqueue>();
            this.adsl_stockmovement = new HashSet<adsl_stockmovement>();
            this.adsl_stockmovement1 = new HashSet<adsl_stockmovement>();
            this.relatedpersonel2 = new HashSet<adsl_personel>();
            this.atama = new HashSet<atama>();
            this.atamaoff = new HashSet<atama>();
            this.kurulumpersonel2 = new HashSet<adsl_personel>();
        }
    
        public int personelid { get; set; }
        public string personelname { get; set; }
        public int category { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string notes { get; set; }
        public int roles { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public int updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> ilKimlikNo { get; set; }
        public Nullable<int> ilceKimlikNo { get; set; }
        public Nullable<int> relatedpersonelid { get; set; }
        public Nullable<int> kurulumpersonelid { get; set; }
        public string responseregions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_taskqueue> attachedTaskqueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_taskqueue> attachedtaskqueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_taskqueue> updatedTaskqueue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_stockmovement> adsl_stockmovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_stockmovement> adsl_stockmovement1 { get; set; }
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_personel> relatedpersonel2 { get; set; }
        public virtual adsl_personel relatedpersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atama> atama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atama> atamaoff { get; set; }
        public virtual adsl_personel kurulumpersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adsl_personel> kurulumpersonel2 { get; set; }
    }
}
