//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class bina
    {
        public Nullable<int> CsbmKimlikNo { get; set; }
        public string aciklama { get; set; }
        public string ada { get; set; }
        public string binaDurum { get; set; }
        public Nullable<int> binaDurumKod { get; set; }
        public string binaNumaratajTipiAciklama { get; set; }
        public Nullable<int> binaNumaratajTipiKod { get; set; }
        public string binaYapiTipiAciklama { get; set; }
        public Nullable<int> binaYapiTipiKod { get; set; }
        public string blokAdi { get; set; }
        public Nullable<int> kapiNo { get; set; }
        public int kimlikNo { get; set; }
        public Nullable<bool> maksIntegrated { get; set; }
        public string pafta { get; set; }
        public string parsel { get; set; }
        public string siteKooperatifAdi { get; set; }
        public Nullable<int> yolKimlikNo { get; set; }
        public Nullable<int> mahalleKoyBaglisiKimlikNo { get; set; }
    }
}
