//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KOCSAMADLSEntities : DbContext
    {
        public KOCSAMADLSEntities()
            : base("name=KOCSAMADLSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bina> bina { get; set; }
        public virtual DbSet<cadde> cadde { get; set; }
        public virtual DbSet<adsl_campaigns> campaigns { get; set; }
        public virtual DbSet<adsl_customer_status> customer_status { get; set; }
        public virtual DbSet<adsl_customerdocument> customerdocument { get; set; }
        public virtual DbSet<adsl_customerproduct> customerproduct { get; set; }
        public virtual DbSet<daire> daire { get; set; }
        public virtual DbSet<adsl_document> document { get; set; }
        public virtual DbSet<adsl_gsmKullanımıStatus> gsmKullanımıStatus { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<adsl_issStatus> issStatus { get; set; }
        public virtual DbSet<mahalleKoy> mahalleKoy { get; set; }
        public virtual DbSet<adsl_mailservices> mailservices { get; set; }
        public virtual DbSet<adsl_netStatus> netStatus { get; set; }
        public virtual DbSet<adsl_objecttypes> objecttypes { get; set; }
        public virtual DbSet<adsl_personel> personel { get; set; }
        public virtual DbSet<adsl_product_service> product_service { get; set; }
        public virtual DbSet<adsl_stockcard> stockcard { get; set; }
        public virtual DbSet<adsl_stockmovement> stockmovement { get; set; }
        public virtual DbSet<adsl_task> task { get; set; }
        public virtual DbSet<adsl_taskqueue> taskqueue { get; set; }
        public virtual DbSet<adsl_taskstatematches> taskstatematches { get; set; }
        public virtual DbSet<adsl_taskstatepool> taskstatepool { get; set; }
        public virtual DbSet<adsl_tasktypes> tasktypes { get; set; }
        public virtual DbSet<customer> customer { get; set; }
    }
}
