//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KOCSAMADLSEntities : DbContext
    {
        public KOCSAMADLSEntities()
            : base("name=KOCSAMADLSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adsl_campaigns> campaigns { get; set; }
        public virtual DbSet<adsl_customer_status> customer_status { get; set; }
        public virtual DbSet<adsl_customerdocument> customerdocument { get; set; }
        public virtual DbSet<adsl_customerproduct> customerproduct { get; set; }
        public virtual DbSet<daire> daire { get; set; }
        public virtual DbSet<adsl_document> document { get; set; }
        public virtual DbSet<adsl_gsmKullanımıStatus> gsmKullanımıStatus { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<adsl_issStatus> issStatus { get; set; }
        public virtual DbSet<adsl_mailservices> mailservices { get; set; }
        public virtual DbSet<adsl_netStatus> netStatus { get; set; }
        public virtual DbSet<adsl_objecttypes> objecttypes { get; set; }
        public virtual DbSet<adsl_personel> personel { get; set; }
        public virtual DbSet<adsl_product_service> product_service { get; set; }
        public virtual DbSet<adsl_stockcard> stockcard { get; set; }
        public virtual DbSet<adsl_stockmovement> stockmovement { get; set; }
        public virtual DbSet<adsl_task> task { get; set; }
        public virtual DbSet<adsl_taskqueue> taskqueue { get; set; }
        public virtual DbSet<adsl_taskstatematches> taskstatematches { get; set; }
        public virtual DbSet<adsl_taskstatepool> taskstatepool { get; set; }
        public virtual DbSet<adsl_tasktypes> tasktypes { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<cadde> cadde { get; set; }
        public virtual DbSet<adsl_vcampaignproducts> vcampaignproducts { get; set; }
        public virtual DbSet<bina> bina { get; set; }
        public virtual DbSet<v_taskorderIsEditable> v_taskorderIsEditable { get; set; }
        public virtual DbSet<bucak> bucak { get; set; }
        public virtual DbSet<mahalleKoy> mahalleKoy { get; set; }
        public virtual DbSet<atama> atama { get; set; }
        public virtual DbSet<SL> SL { get; set; }
        public virtual DbSet<paymentsystem> paymentsystem { get; set; }
        public virtual DbSet<paymentsystemtype> paymentsystemtype { get; set; }
    
        [DbFunction("KOCSAMADLSEntities", "getSerialsOnPersonelAdsl")]
        public virtual IQueryable<string> getSerialsOnPersonelAdsl(Nullable<int> pERSONELID, Nullable<int> sTOCKCARDID)
        {
            var pERSONELIDParameter = pERSONELID.HasValue ?
                new ObjectParameter("PERSONELID", pERSONELID) :
                new ObjectParameter("PERSONELID", typeof(int));
    
            var sTOCKCARDIDParameter = sTOCKCARDID.HasValue ?
                new ObjectParameter("STOCKCARDID", sTOCKCARDID) :
                new ObjectParameter("STOCKCARDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[KOCSAMADLSEntities].[getSerialsOnPersonelAdsl](@PERSONELID, @STOCKCARDID)", pERSONELIDParameter, sTOCKCARDIDParameter);
        }
    
        [DbFunction("KOCSAMADLSEntities", "getPersonelStockAdsl")]
        public virtual IQueryable<getPersonelStockAdsl_Result> getPersonelStockAdsl(Nullable<int> pERSONELID)
        {
            var pERSONELIDParameter = pERSONELID.HasValue ?
                new ObjectParameter("PERSONELID", pERSONELID) :
                new ObjectParameter("PERSONELID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getPersonelStockAdsl_Result>("[KOCSAMADLSEntities].[getPersonelStockAdsl](@PERSONELID)", pERSONELIDParameter);
        }
    
        [DbFunction("KOCSAMADLSEntities", "getSerialsOnCustomerAdsl")]
        public virtual IQueryable<string> getSerialsOnCustomerAdsl(Nullable<int> cUSTOMERID, Nullable<int> sTOCKCARDID)
        {
            var cUSTOMERIDParameter = cUSTOMERID.HasValue ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(int));
    
            var sTOCKCARDIDParameter = sTOCKCARDID.HasValue ?
                new ObjectParameter("STOCKCARDID", sTOCKCARDID) :
                new ObjectParameter("STOCKCARDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[KOCSAMADLSEntities].[getSerialsOnCustomerAdsl](@CUSTOMERID, @STOCKCARDID)", cUSTOMERIDParameter, sTOCKCARDIDParameter);
        }
    
        [DbFunction("KOCSAMADLSEntities", "getCustomerStockAdsl")]
        public virtual IQueryable<getCustomerStockAdsl_Result> getCustomerStockAdsl(Nullable<int> cUSTOMERID)
        {
            var cUSTOMERIDParameter = cUSTOMERID.HasValue ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getCustomerStockAdsl_Result>("[KOCSAMADLSEntities].[getCustomerStockAdsl](@CUSTOMERID)", cUSTOMERIDParameter);
        }
    }
}
