//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class daire
    {
        public int kimlikNo { get; set; }
        public Nullable<int> binaKimlikNo { get; set; }
        public Nullable<int> mahalleKoyBaglisiKimlikNo { get; set; }
        public string aciklama { get; set; }
        public string bagimsizBolumNo { get; set; }
        public Nullable<bool> maksIntegrated { get; set; }
    }
}
