//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahalleKoy
    {
        public int kimlikNo { get; set; }
        public string mahalleAciklama { get; set; }
        public Nullable<int> koyKimlikNo { get; set; }
        public string koyAciklama { get; set; }
        public Nullable<int> koyKurumTur { get; set; }
        public Nullable<int> bucakKimlikNo { get; set; }
        public string bucakAciklama { get; set; }
        public Nullable<int> ilceKimlikNo { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> maksIntegrated { get; set; }
    }
}
