//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentsystem
    {
        public int id { get; set; }
        public int paymentType { get; set; }
        public Nullable<double> payment { get; set; }
        public Nullable<int> upperLimitAmount { get; set; }
        public Nullable<int> upperLimitSL { get; set; }
    
        public virtual paymentsystemtype paymentsystemtype { get; set; }
    }
}
