//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL
    {
        public int SLID { get; set; }
        public string SLName { get; set; }
        public string KocSTask { get; set; }
        public string KocETask { get; set; }
        public string BayiSTask { get; set; }
        public string BayiETask { get; set; }
        public System.DateTime lastupdated { get; set; }
        public int updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> KocMaxTime { get; set; }
        public Nullable<int> BayiMaxTime { get; set; }
    }
}
