//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Adsl
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSContent
    {
        public int Cid { get; set; }
        public long Id { get; set; }
        public string MSISDN { get; set; }
        public int Network { get; set; }
        public double Cost { get; set; }
        public System.DateTime Submitted { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string State { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string Payload { get; set; }
        public string Xser { get; set; }
    }
}
