//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class atama
    {
        public int id { get; set; }
        public Nullable<int> closedtasktype { get; set; }
        public Nullable<int> closedtask { get; set; }
        public Nullable<int> offpersonel { get; set; }
        public Nullable<int> formedtasktype { get; set; }
        public Nullable<int> formedtask { get; set; }
        public Nullable<int> appointedpersonel { get; set; }
    
        public virtual task taskformed { get; set; }
        public virtual task taskclosed { get; set; }
        public virtual personel personeloff { get; set; }
        public virtual personel personelappointed { get; set; }
        public virtual tasktypes tasktypesclosed { get; set; }
        public virtual tasktypes tasktypesformed { get; set; }
    }
}
