//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public block()
        {
            this.customers = new HashSet<customer>();
            this.taskqueues = new HashSet<taskqueue>();
        }
    
        public int blockid { get; set; }
        public string blockname { get; set; }
        public int siteid { get; set; }
        public string groupid { get; set; }
        public Nullable<int> hp { get; set; }
        public string telocadia { get; set; }
        public string projectno { get; set; }
        public Nullable<System.DateTime> readytosaledate { get; set; }
        public Nullable<System.DateTime> sosaledate { get; set; }
        public Nullable<System.DateTime> kocsaledate { get; set; }
        public Nullable<int> salesrepresentative { get; set; }
        public string superintendent { get; set; }
        public string superintendentcontact { get; set; }
        public string cocierge { get; set; }
        public string cociergecontact { get; set; }
        public string verticalproductionline { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public int updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string binakodu { get; set; }
        public string locationid { get; set; }
        public string objid { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<taskqueue> taskqueues { get; set; }
        public virtual site site { get; set; }
        public virtual personel updatedpersonel { get; set; }
        public virtual personel salespersonel { get; set; }
    }
}
