//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerinfo
    {
        public int customerid { get; set; }
        public string sitename { get; set; }
        public string blockname { get; set; }
        public string flat { get; set; }
        public string customerinfo1 { get; set; }
        public string gsm { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> sosaledate { get; set; }
        public Nullable<System.DateTime> contratfinish { get; set; }
        public Nullable<int> emptorcustomernum { get; set; }
    }
}
