//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class flatinfo
    {
        public int customerid { get; set; }
        public string flatinfo1 { get; set; }
        public Nullable<int> blockid { get; set; }
        public string flat { get; set; }
    }
}
