//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class netStatus
    {
        public netStatus()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int id { get; set; }
        public string netText { get; set; }
        public Nullable<int> deleted { get; set; }
    
        public virtual ICollection<customer> customer { get; set; }
    }
}
