//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public personel()
        {
            this.attachedtaskqueues = new HashSet<taskqueue>();
            this.attachedTaskqueuesAsistant = new HashSet<taskqueue>();
            this.updateTaskqueues = new HashSet<taskqueue>();
            this.updateblocks = new HashSet<block>();
            this.updatecustomers = new HashSet<customer>();
            this.updatesites = new HashSet<site>();
            this.updatetasks = new HashSet<task>();
            this.updatetaskstatepools = new HashSet<taskstatepool>();
            this.blocks = new HashSet<block>();
            this.stockmovement = new HashSet<stockmovement>();
            this.stockmovement1 = new HashSet<stockmovement>();
            this.stockstatus = new HashSet<stockstatus>();
            this.atamaoffpersonel = new HashSet<atama>();
            this.appointedpersonelatama = new HashSet<atama>();
        }
    
        public int personelid { get; set; }
        public string personelname { get; set; }
        public Nullable<int> category { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string notes { get; set; }
        public Nullable<int> roles { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<taskqueue> attachedtaskqueues { get; set; }
        public virtual ICollection<taskqueue> attachedTaskqueuesAsistant { get; set; }
        public virtual ICollection<taskqueue> updateTaskqueues { get; set; }
        public virtual ICollection<block> updateblocks { get; set; }
        public virtual ICollection<customer> updatecustomers { get; set; }
        public virtual ICollection<site> updatesites { get; set; }
        public virtual ICollection<task> updatetasks { get; set; }
        public virtual ICollection<taskstatepool> updatetaskstatepools { get; set; }
        public virtual ICollection<block> blocks { get; set; }
        public virtual ICollection<stockmovement> stockmovement { get; set; }
        public virtual ICollection<stockmovement> stockmovement1 { get; set; }
        public virtual ICollection<stockstatus> stockstatus { get; set; }
        public virtual ICollection<atama> atamaoffpersonel { get; set; }
        public virtual ICollection<atama> appointedpersonelatama { get; set; }
    }
}
