//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Fiber
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasktypes
    {
        public tasktypes()
        {
            this.task = new HashSet<task>();
        }
    
        public int TaskTypeId { get; set; }
        public string TaskTypeName { get; set; }
    
        public virtual ICollection<task> task { get; set; }
    }
}
