//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models.Cari
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariHareketler
    {
        public int Id { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> İslemTarihiYıl { get; set; }
        public Nullable<int> İslemTarihiAy { get; set; }
        public Nullable<int> İslemTarihiGun { get; set; }
        public string AlacakliFirma { get; set; }
        public string BorcluFirma { get; set; }
        public string OdemeKalemi { get; set; }
        public decimal Tutar { get; set; }
        public decimal KdvMatrah { get; set; }
        public System.DateTime Donem { get; set; }
        public Nullable<int> DonemYıl { get; set; }
        public Nullable<int> DonemAy { get; set; }
        public Nullable<int> DonemGun { get; set; }
        public System.DateTime VadeTarihi { get; set; }
        public Nullable<int> VadeYıl { get; set; }
        public Nullable<int> VadeAy { get; set; }
        public Nullable<int> VadeGun { get; set; }
        public string Aciklama { get; set; }
    }
}
