//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaigns
    {
        public campaigns()
        {
            this.customerproduct = new HashSet<customerproduct>();
        }
    
        public int id { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string name { get; set; }
        public string products { get; set; }
        public string documents { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<customerproduct> customerproduct { get; set; }
    }
}
