//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objecttypes
    {
        public objecttypes()
        {
            this.stockmovement = new HashSet<stockmovement>();
            this.stockmovement1 = new HashSet<stockmovement>();
            this.task = new HashSet<task>();
            this.task1 = new HashSet<task>();
        }
    
        public int typeid { get; set; }
        public string typname { get; set; }
    
        public virtual ICollection<stockmovement> stockmovement { get; set; }
        public virtual ICollection<stockmovement> stockmovement1 { get; set; }
        public virtual ICollection<task> task { get; set; }
        public virtual ICollection<task> task1 { get; set; }
    }
}
