//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public site()
        {
            this.blocks = new HashSet<block>();
        }
    
        public int siteid { get; set; }
        public string sitename { get; set; }
        public string siteaddress { get; set; }
        public string region { get; set; }
        public string sitedistrict { get; set; }
        public string siteregioncode { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<block> blocks { get; set; }
        public virtual personel updatedpersonel { get; set; }
    }
}
