//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockmovement
    {
        public int movementid { get; set; }
        public Nullable<int> relatedtaskqueue { get; set; }
        public Nullable<int> fromobjecttype { get; set; }
        public Nullable<int> fromobject { get; set; }
        public Nullable<int> toobjecttype { get; set; }
        public Nullable<int> toobject { get; set; }
        public Nullable<int> stockcardid { get; set; }
        public Nullable<int> amount { get; set; }
        public string serialno { get; set; }
        public Nullable<System.DateTime> movementdate { get; set; }
        public Nullable<System.DateTime> confirmationdate { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual stockcard stockcard { get; set; }
        public virtual customer tocustomer { get; set; }
        public virtual taskqueue taskqueue { get; set; }
        public virtual objecttypes fromobjecttypes { get; set; }
        public virtual objecttypes toobjecttypes { get; set; }
        public virtual customer fromcustomer { get; set; }
        public virtual personel frompersonel { get; set; }
        public virtual personel topersonel { get; set; }
    }
}
