//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskstatematches
    {
        public int id { get; set; }
        public Nullable<int> taskid { get; set; }
        public Nullable<int> stateid { get; set; }
        public string automandatorytasks { get; set; }
        public string autooptionaltasks { get; set; }
        public string stockcards { get; set; }
        public string documents { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual task task { get; set; }
        public virtual taskstatepool taskstatepool { get; set; }
    }
}
