//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.taskqueues = new HashSet<taskqueue>();
        }
    
        public int taskid { get; set; }
        public string taskname { get; set; }
        public int tasktype { get; set; }
        public Nullable<int> attachablepersoneltype { get; set; }
        public Nullable<int> attachableobjecttype { get; set; }
        public Nullable<double> performancescore { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public Nullable<int> updatedby { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<taskqueue> taskqueues { get; set; }
        public virtual personel updatedpersonel { get; set; }
        public virtual tasktypes tasktypes { get; set; }
    }
}
