//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcampaignproducts
    {
        public int cid { get; set; }
        public int pid { get; set; }
        public string cname { get; set; }
        public string productname { get; set; }
    
        public virtual campaigns campaigns { get; set; }
        public virtual product_service product_service { get; set; }
    }
}
